CREATE TABLE member
(
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(50) NOT NULL,
  age            SMALLINT
    CONSTRAINT positive_age CHECK (age > 0),
  is_gender_male BOOLEAN
);
CREATE TABLE relation
(
  id                  SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation            VARCHAR(20) NOT NULL,
  is_generic_relation BOOLEAN
);

CREATE TABLE relation_line
(
  to_member_id   bigint REFERENCES member,
  from_member_id bigint REFERENCES member,
  relation SMALLINT REFERENCES relation
);

